"""Pydantic response models.

These models define the exact JSON shape the API returns and guarantee that
internal details (API keys, paths, stack traces) can never leak into responses.
"""

from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, Field


class SourceReferenceResponse(BaseModel):
    """A de-duplicated, human-readable citation for one answer."""

    document: str = Field(description="Source filename, e.g. employee_handbook.pdf")
    page: int | str | None = Field(
        default=None, description="Page number where available"
    )
    section: str | None = Field(default=None, description="Section / chunk title")
    relevance_score: float = Field(
        default=0.0, ge=0.0, le=1.0, description="Cosine relevance of the chunk"
    )


class RetrievedChunkResponse(BaseModel):
    """Full retrieved chunk (context + metadata + relevance)."""

    content: str
    metadata: dict[str, Any]
    score: float


class ChatResponse(BaseModel):
    """Response of the POST /chat endpoint."""

    answer: str = Field(description="Grounded answer generated by the RAG pipeline")
    sources: list[SourceReferenceResponse] = Field(
        default_factory=list,
        description="De-duplicated source citations into the retrieved documents",
    )
    retrieved_context_count: int = Field(
        default=0,
        description="Number of grounded context chunks above the relevance threshold",
    )
    model: str = Field(description="Gemini model used for generation")
    latency_ms: int = Field(description="End-to-end latency of the RAG query in ms")
    retrieved_chunks: list[RetrievedChunkResponse] = Field(
        default_factory=list,
        description="The actual retrieved chunks used to ground the answer",
    )


class DocumentInfoResponse(BaseModel):
    """Metadata describing one indexed document."""

    filename: str
    chunk_count: int
    ingested_at: str | None = None


class DocumentListResponse(BaseModel):
    """Response of GET /documents."""

    documents: list[DocumentInfoResponse] = Field(default_factory=list)
    total_documents: int
    total_chunks: int


class IngestResponse(BaseModel):
    """Response of POST /documents/ingest."""

    status: Literal["ok"]
    files_found: int
    files_processed: int
    files_skipped_unchanged: int
    chunks_added: int
    chunks_skipped_duplicate: int
    failures: list[dict[str, Any]] = Field(default_factory=list)


class DocumentSummaryResponse(BaseModel):
    """Response of POST /documents/{document_name}/summary."""

    document: str = Field(description="Source filename, e.g. leave_policy.txt")
    chunk_count: int = Field(
        description="Number of indexed chunks used to build the summary"
    )
    summary: str = Field(description="Generated summary of the document")
    model: str = Field(description="Gemini model used for generation")


class HealthResponse(BaseModel):
    """Response of GET /health."""

    status: str
    app_name: str
    version: str
    components: dict[str, Any]


__all__ = [
    "ChatResponse",
    "SourceReferenceResponse",
    "RetrievedChunkResponse",
    "DocumentInfoResponse",
    "DocumentListResponse",
    "IngestResponse",
    "DocumentSummaryResponse",
    "HealthResponse",
]